const animals = [
  { name: "반달가슴곰", grade: "grade1", desc: "지리산을 중심으로 복원 사업이 진행 중인 대한민국 대표 대형 포유류.", image: "https://tse4.mm.bing.net/th/id/OIP.yrkJGyLOr7WTzGUcE9wj7wHaGL?rs=1&pid=ImgDetMain&o=7&rm=3" },
  { name: "산양", grade: "grade1", desc: "험준한 산악지대에 서식하는 희귀 포유류로 천연기념물로도 지정되어 있다.", image: "https://upload.wikimedia.org/wikipedia/commons/4/4c/Nemorhaedus_caudatus.jpg" },
  { name: "여우", grade: "grade1", desc: "과거 한반도 전역에 서식했으며 현재 복원 사업이 진행되고 있다.", image: "https://upload.wikimedia.org/wikipedia/commons/7/7d/Korean_fox.jpeg" },
  { name: "수달", grade: "grade1", desc: "깨끗한 강과 하천에 서식하는 생태계 건강 지표종이다.", image: "https://i.namu.wiki/i/9T4Hi6qeZFZ0FF5iVJgf6bM4QCjMvjTtG7YDC_MwSNIsuk6MoBuvrAA9GOVENU80IYkbEj_s4Xr8_06nk-O6Cg.webp" },
  { name: "두루미", grade: "grade1", desc: "철원과 DMZ 일대에서 관찰되는 대표적인 겨울 철새이다.", image: "https://i.namu.wiki/i/YsKgAq-bTGI-nqt7NahiNVZZ71rQQWrwvNhBNp9LXb081nIj8nz6KD8C2T6cGg7Yyz5K_8JrNMYNQ0zh8iPZ-w.webp" },
  { name: "저어새", grade: "grade1", desc: "주걱 모양의 부리를 가진 희귀 조류로 세계적으로도 개체 수가 적다.", image: "https://i.namu.wiki/i/Wp9NpnGtGMEYHICywSjn5nkpaebCaaa1D5n_0cB-H_-XFxzM5iS42kJha-SzyBYNYeWZk1F3MxAdk_S6zBb60A.webp" },
  { name: "노랑부리저어새", grade: "grade1", desc: "노란 부리가 특징인 대형 물새로 갯벌과 습지에 서식한다.", image: "https://i.namu.wiki/i/ygpmFJmXU0zPxdb_580PG2oc28C7Btw4L5EyGOFcZEJsLkS2negU0vBWxeZgb2G5I0eepvVWEZJxJZoVD5udpA.webp" },
  { name: "황새", grade: "grade1", desc: "한때 국내에서 사라졌다가 복원 사업을 통해 다시 방사되고 있다.", image: "https://i.namu.wiki/i/VUIpMpoTKNk6funf0UYGUtscdhsv9lV2NrnuurDnbfyH4KRbLdggOv0c1ux_xkTFlCD2InE3VVrUvZOAPthfEA.webp" },
  { name: "참수리", grade: "grade1", desc: "대형 맹금류로 겨울철 한국을 찾는 희귀한 새이다.", image: "https://busan.grandculture.net/ImageView.aspx?fi=GC042P56192&t=middle&ext=jpg&iwm=1" },
  { name: "검독수리", grade: "grade1", desc: "산악지대에서 살아가는 최상위 포식자 중 하나이다.", image: "https://i.namu.wiki/i/s8DeBPGZAFh_zRf8uLrCBPEi0r0NRCY5v27mx6Wb6JCuqnJwGkfRvHKEZAWgIgEO157vuCla9c_GeKIoZ85hLg.webp" },
  { name: "매", grade: "grade1", desc: "빠른 비행 속도로 유명한 대표적인 맹금류이다.", image: "https://i.namu.wiki/i/SEu_OUxugasfIdM4cCoeZYpkV8YgRRTPEcw8BDSZHAxV2rSV3d54GWIdxlIGvMLUMyJmoVXNqro_cFdxO_pLAQ.webp" },
  { name: "붉은점모시나비", grade: "grade1", desc: "붉은 무늬가 특징인 아름다운 고산지대 나비이다.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRWHU54XrMSiET69WxGvgjNEnvtVSiWicvrnA&s" },
  { name: "꼬치동자개", grade: "grade1", desc: "우리나라 고유의 민물고기로 깨끗한 하천에 서식한다.", image: "https://i.namu.wiki/i/AjyWjgmb6wclR5EA6jn43jKAhWwFNAAff8YjQrky5whaSL54TOx6AlrSNDs_mVfXranXuowkAyuO76V41OKAEA.webp" },
  { name: "미호종개", grade: "grade1", desc: "금강 수계에 주로 서식하는 한국 고유 어종이다.", image: "https://www.ecotiger.co.kr/news/photo/201703/20028_17545_5851.jpg" },
  { name: "귀이빨대칭이", grade: "grade1", desc: "강바닥에 사는 희귀한 민물조개이다.", image: "https://img.sbs.co.kr/newimg/news/20200515/201431309_500.jpg" },
  { name: "삵", grade: "grade2", desc: "우리나라에 서식하는 야생 고양잇과 동물이다.", image: "https://i.namu.wiki/i/xgiZB8vWTDpNP0Fw2JyygBB0PlV_dUDnY2aaRcpN9SazpE0wqLpKTs1jocjtIKZ3QHlTkz-ocEmE9j3yXXG9TA.webp" },
  { name: "담비", grade: "grade2", desc: "산림 생태계에서 중요한 역할을 하는 육식성 포유류이다.", image: "https://i.namu.wiki/i/dN6Ugly8v9dndtf2nvSrcTGnBQMVNgQvWxv2Qvq5eXSW7oG1ZoQk9FvT83TWQlFmacB7Kyzk8rWoDYYEd56qlw.webp" },
  { name: "물범", grade: "grade2", desc: "백령도 인근 해역에서 주로 발견되는 해양 포유류이다.", image: "https://lh5.googleusercontent.com/proxy/eusZnIuo_jVZLbR1FzBBFnwwa2sLhuziSBAD-f9sHEENzmtyCLcrOWntLxEk2wi1IZR_79ajTnsMlAJFmZ1_3b58Rb6nUBlocI_qRLKXG88" },
  { name: "재두루미", grade: "grade2", desc: "두루미와 비슷한 대형 철새로 겨울철에 찾아온다.", image: "https://i.namu.wiki/i/-JET_Clg1SNqKZfJQPR0lP5KyszRwUwbnlsWS_SilIacu49FZ1zpUdXhlyeR5s2ZDK2Ww79Oej-PGZ_6rEYFsg.webp" },
  { name: "새매", grade: "grade2", desc: "숲에서 주로 생활하는 중형 맹금류이다.", image: "https://www.heritage.go.kr/unisearch/images/natural_monument/thumb/1632903.jpg" },
  { name: "독수리", grade: "grade2", desc: "겨울철 한국을 찾는 대형 맹금류이다.", image: "https://i.namu.wiki/i/q8LMFkwkDh_U2B4ibahlVTmks5eTQnQDFf_b1z22fLEMUmb4JQmOp5JM3TkUwr_zGExn26C3KLtuc31p2_fSwg.webp" },
  { name: "청호반새", grade: "grade2", desc: "푸른 깃털이 아름다운 여름철새이다.", image: "https://i.namu.wiki/i/gNO1_y9MD0qf6_1Frqcay7QHidWcvDEZM68MheJEGCXq92ofsUC2gmuGpkk9H9qL7_CV6PPWKCKMUdMnZoC6Fg.webp" },
  { name: "금개구리", grade: "grade2", desc: "논과 습지에서 살아가는 한국의 희귀 양서류이다.", image: "https://species.nibr.go.kr/gwsvc/digital/api/v1/minio/view?filePath=species/12000016/120000164710/BIMGAM0000376668_20211105112431304132.jpg" },
  { name: "수원청개구리", grade: "grade2", desc: "경기 지역을 중심으로 서식하는 한국 고유종 개구리이다.", image: "https://species.nibr.go.kr/gwsvc/digital/api/v1/minio/view?filePath=species/12000047/120000474038/PC_20211116162037_TPQYTLQKIA.jpg" },
  { name: "맹꽁이", grade: "grade2", desc: "독특한 울음소리로 유명한 양서류이다.", image: "https://i.namu.wiki/i/-NkF7le6D-zz-eds9UpU8C97D-PgEGOAKMczciAm52YM_j5b7JSiB1PVZUC1zEIqe9_VRDU4FBH_MjHI3HjvbQ.webp" },
  { name: "남생이", grade: "grade2", desc: "우리나라 토종 민물거북이다.", image: "https://i.namu.wiki/i/-5NXXkGS6GRM_nt_8uvGUohEac4fU13G4hboxdBhs9iPP2nKLO11DWDMld_gvk4nvwcAO15acjx8CUICCpbjHg.webp" },
  { name: "감돌고기", grade: "grade2", desc: "맑은 하천에 서식하는 작은 민물고기이다.", image: "https://ecolink.or.kr/ecosystem/resources/images/%EA%B0%90%EB%8F%8C%EA%B3%A0%EA%B8%B0.jpg" },
  { name: "흰수마자", grade: "grade2", desc: "한강 수계에 서식하는 희귀 어종이다.", image: "https://cphoto.asiae.co.kr/listimglink/1/2024070810180943180_1720401488.jpg" },
  { name: "긴다리소똥구리", grade: "grade2", desc: "과거 농촌에서 흔했지만 현재는 보기 어려운 곤충이다.", image: "https://ilyo.co.kr/contents/article/images/2013/0611/1370928900573140.jpg" },
  { name: "애기뿔소똥구리", grade: "grade2", desc: "소똥을 이용해 살아가는 희귀 곤충이다.", image: "https://www.ccnnews.co.kr/news/photo/202406/339396_423289_2620.jpg" },
];